services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ETL_USER_PASSWORD: ${ETL_USER_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}      
    ports:
      - "5432:5432"
    volumes:      
      - db_data:/var/lib/postgresql
      - ./schema/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./schema:/app/schema
  tangerine:
    build: .
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}

volumes:
  db_data: